# ==============================================================================
# Merged Lakeflow Source: quickbooks
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from __future__ import annotations
from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from email.utils import parsedate_to_datetime
from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import random
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/quickbooks/quickbooks_schemas.py
    ########################################################

    _DECIMAL = DecimalType(38, 9)


    def _common_fields() -> list[StructField]:
        return [
            StructField("realm_id", StringType(), nullable=False),
            StructField("id", StringType(), nullable=False),
            StructField("sync_token", StringType(), nullable=True),
            StructField("created_at", TimestampType(), nullable=True),
            StructField("last_updated_at", TimestampType(), nullable=True),
        ]


    def _schema(*fields: StructField) -> StructType:
        return StructType([*_common_fields(), *fields, StructField("raw_json", StringType(), False)])


    TABLE_SCHEMAS = {
        "customers": _schema(
            StructField("display_name", StringType(), True),
            StructField("company_name", StringType(), True),
            StructField("given_name", StringType(), True),
            StructField("family_name", StringType(), True),
            StructField("primary_email", StringType(), True),
            StructField("primary_phone", StringType(), True),
            StructField("balance", _DECIMAL, True),
            StructField("currency_ref", StringType(), True),
            StructField("active", BooleanType(), True),
        ),
        "vendors": _schema(
            StructField("display_name", StringType(), True),
            StructField("company_name", StringType(), True),
            StructField("given_name", StringType(), True),
            StructField("family_name", StringType(), True),
            StructField("primary_email", StringType(), True),
            StructField("primary_phone", StringType(), True),
            StructField("balance", _DECIMAL, True),
            StructField("vendor_1099", BooleanType(), True),
            StructField("currency_ref", StringType(), True),
            StructField("active", BooleanType(), True),
        ),
        "accounts": _schema(
            StructField("name", StringType(), True),
            StructField("fully_qualified_name", StringType(), True),
            StructField("account_type", StringType(), True),
            StructField("account_sub_type", StringType(), True),
            StructField("classification", StringType(), True),
            StructField("current_balance", _DECIMAL, True),
            StructField("currency_ref", StringType(), True),
            StructField("active", BooleanType(), True),
        ),
        "items": _schema(
            StructField("name", StringType(), True),
            StructField("fully_qualified_name", StringType(), True),
            StructField("item_type", StringType(), True),
            StructField("description", StringType(), True),
            StructField("unit_price", _DECIMAL, True),
            StructField("purchase_cost", _DECIMAL, True),
            StructField("quantity_on_hand", _DECIMAL, True),
            StructField("income_account_ref", StringType(), True),
            StructField("expense_account_ref", StringType(), True),
            StructField("asset_account_ref", StringType(), True),
            StructField("active", BooleanType(), True),
        ),
        "invoices": _schema(
            StructField("doc_number", StringType(), True),
            StructField("txn_date", DateType(), True),
            StructField("due_date", DateType(), True),
            StructField("customer_ref", StringType(), True),
            StructField("total_amount", _DECIMAL, True),
            StructField("balance", _DECIMAL, True),
            StructField("currency_ref", StringType(), True),
            StructField("email_status", StringType(), True),
            StructField("print_status", StringType(), True),
            StructField("line_json", StringType(), True),
        ),
        "bills": _schema(
            StructField("doc_number", StringType(), True),
            StructField("txn_date", DateType(), True),
            StructField("due_date", DateType(), True),
            StructField("vendor_ref", StringType(), True),
            StructField("total_amount", _DECIMAL, True),
            StructField("balance", _DECIMAL, True),
            StructField("currency_ref", StringType(), True),
            StructField("ap_account_ref", StringType(), True),
            StructField("line_json", StringType(), True),
        ),
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/quickbooks/quickbooks.py
    ########################################################

    TABLE_TO_ENTITY = {
        "customers": "Customer",
        "vendors": "Vendor",
        "accounts": "Account",
        "items": "Item",
        "invoices": "Invoice",
        "bills": "Bill",
    }
    LIST_TABLES = frozenset({"customers", "vendors", "accounts", "items"})
    DELETABLE_TABLES = frozenset({"invoices", "bills"})

    RETRIABLE_STATUS_CODES = frozenset({429, 500, 502, 503, 504})
    DEFAULT_PAGE_SIZE = 1000
    DEFAULT_TIMEOUT_SECONDS = 30
    DEFAULT_MAX_RETRIES = 5
    DEFAULT_INCREMENTAL_OVERLAP_SECONDS = 60
    DEFAULT_MAX_INCREMENTAL_WINDOW_SECONDS = 86400
    DEFAULT_DELETE_OVERLAP_SECONDS = 60
    DEFAULT_INITIAL_DELETE_LOOKBACK_SECONDS = 300
    MAX_CDC_LOOKBACK_SECONDS = 30 * 86400
    MAX_CDC_OBJECTS = 1000
    OFFSET_VERSION = 2
    OFFSET_VERSION_KEY = "version"
    OFFSET_CURSOR_KEY = "updated_through"
    OFFSET_REALM_KEY = "realm_id"
    OFFSET_TABLE_KEY = "table_name"
    OFFSET_FLOW_KEY = "flow"
    CURSOR_FIELD = "last_updated_at"


    class QuickBooksApiClient:
        """Small, stateless QuickBooks Online query client."""

        def __init__(
            self,
            *,
            access_token: str,
            realm_id: str,
            environment: str,
            minor_version: int,
            timeout_seconds: int = DEFAULT_TIMEOUT_SECONDS,
            max_retries: int = DEFAULT_MAX_RETRIES,
        ) -> None:
            if environment not in {"sandbox", "production"}:
                raise ValueError("environment must be 'sandbox' or 'production'")
            self._access_token = access_token
            self._realm_id = realm_id
            self._environment = environment
            self._minor_version = minor_version
            self._timeout_seconds = timeout_seconds
            self._max_retries = max_retries

        @property
        def _base_url(self) -> str:
            if self._environment == "sandbox":
                return "https://sandbox-quickbooks.api.intuit.com"
            return "https://quickbooks.api.intuit.com"

        def iter_entity(
            self,
            entity: str,
            *,
            page_size: int,
            where_clause: str | None = None,
        ) -> Iterator[dict]:
            """Yield a complete positional QuickBooks query one page at a time."""
            start_position = 1
            while True:
                query = f"SELECT * FROM {entity}"
                if where_clause:
                    query += f" WHERE {where_clause}"
                query += f" STARTPOSITION {start_position} MAXRESULTS {page_size}"
                body = self._get_query(query)
                page = body.get("QueryResponse", {}).get(entity, [])
                if not isinstance(page, list):
                    raise RuntimeError(f"QuickBooks {entity} query returned an invalid row collection")
                yield from (row for row in page if isinstance(row, dict))
                if len(page) < page_size:
                    return
                start_position += page_size

        def get_entity_changes(self, entity: str, *, changed_since: str) -> tuple[list[dict], str]:
            """Return one entity's recent CDC objects and the server response time."""
            url = f"{self._base_url}/v3/company/{self._realm_id}/cdc"
            payload = self._get(
                url,
                params={
                    "entities": entity,
                    "changedSince": changed_since,
                    "minorversion": str(self._minor_version),
                },
                operation="CDC request",
            )
            cdc_responses = payload.get("CDCResponse")
            if not isinstance(cdc_responses, list):
                raise RuntimeError("QuickBooks CDC returned an invalid CDCResponse")

            rows: list[dict] = []
            reported_count = 0
            for cdc_response in cdc_responses:
                if not isinstance(cdc_response, dict):
                    raise RuntimeError("QuickBooks CDC returned an invalid response entry")
                query_responses = cdc_response.get("QueryResponse", [])
                if not isinstance(query_responses, list):
                    raise RuntimeError("QuickBooks CDC returned an invalid QueryResponse")
                for query_response in query_responses:
                    if not isinstance(query_response, dict):
                        raise RuntimeError("QuickBooks CDC returned an invalid query entry")
                    entity_rows = query_response.get(entity, [])
                    if not isinstance(entity_rows, list):
                        raise RuntimeError(
                            f"QuickBooks CDC returned an invalid {entity} row collection"
                        )
                    rows.extend(row for row in entity_rows if isinstance(row, dict))
                    for count_key in ("maxResults", "totalCount"):
                        count = query_response.get(count_key)
                        if isinstance(count, int):
                            reported_count = max(reported_count, count)

            if len(rows) >= MAX_CDC_OBJECTS or reported_count >= MAX_CDC_OBJECTS:
                raise RuntimeError(
                    "QuickBooks CDC reached its 1,000-object response limit; "
                    "the delete checkpoint was not advanced. Run ingestion more "
                    "frequently or perform a full reconciliation."
                )

            response_time = payload.get("time")
            if not isinstance(response_time, str):
                raise RuntimeError("QuickBooks CDC response is missing its server time")
            return rows, _format_qbo_datetime(_parse_qbo_datetime(response_time))

        def _get_query(self, query: str) -> dict:
            url = f"{self._base_url}/v3/company/{self._realm_id}/query"
            return self._get(
                url,
                params={"query": query, "minorversion": str(self._minor_version)},
                operation="query",
            )

        def _get(self, url: str, *, params: dict[str, str], operation: str) -> dict:
            headers = {
                "Accept": "application/json",
                "Authorization": f"Bearer {self._access_token}",
            }

            for attempt in range(self._max_retries):
                try:
                    response = requests.get(
                        url,
                        headers=headers,
                        params=params,
                        timeout=self._timeout_seconds,
                    )
                except requests.RequestException as exc:
                    if attempt == self._max_retries - 1:
                        raise RuntimeError("QuickBooks request failed after retry exhaustion") from exc
                    self._sleep_before_retry(attempt, None)
                    continue

                if response.status_code in {401, 403}:
                    raise PermissionError(
                        "QuickBooks authentication failed; refresh or recreate the "
                        "Unity Catalog connection"
                    )
                if response.status_code not in RETRIABLE_STATUS_CODES:
                    try:
                        response.raise_for_status()
                    except requests.HTTPError as exc:
                        raise RuntimeError(
                            f"QuickBooks {operation} failed with HTTP {response.status_code}"
                        ) from exc
                    try:
                        payload = response.json()
                    except ValueError as exc:
                        raise RuntimeError("QuickBooks returned an invalid JSON response") from exc
                    if not isinstance(payload, dict):
                        raise RuntimeError("QuickBooks returned an invalid JSON object")
                    return payload

                if attempt == self._max_retries - 1:
                    raise RuntimeError(
                        "QuickBooks request failed after retry exhaustion "
                        f"(HTTP {response.status_code})"
                    )
                self._sleep_before_retry(attempt, response.headers.get("Retry-After"))

            raise AssertionError("unreachable retry state")

        @staticmethod
        def _sleep_before_retry(attempt: int, retry_after: str | None) -> None:
            delay = _retry_after_seconds(retry_after)
            if delay is None:
                delay = min(2**attempt, 30) + random.uniform(0, 0.25)
            time.sleep(delay)


    class QuickBooksLakeflowConnect(LakeflowConnect):
        """QuickBooks connector with checkpointed incremental-update support."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            access_token = options.get("access_token", "").strip()
            realm_id = options.get("realm_id", "").strip()
            if not access_token:
                raise ValueError(
                    "QuickBooks requires an access_token injected by the Unity Catalog OAuth connection"
                )
            if not realm_id:
                raise ValueError("QuickBooks requires realm_id for the authorized company")
            self._realm_id = realm_id

            self._client = QuickBooksApiClient(
                access_token=access_token,
                realm_id=realm_id,
                environment=options.get("environment", "production").strip().lower(),
                minor_version=int(options.get("minor_version", "75")),
                timeout_seconds=int(options.get("timeout_seconds", str(DEFAULT_TIMEOUT_SECONDS))),
                max_retries=int(options.get("max_retries", str(DEFAULT_MAX_RETRIES))),
            )
            # Freeze the upper bound for this Data Source instance. AvailableNow
            # must converge instead of chasing records written while it is running.
            self._init_ts = _format_qbo_datetime(_utc_now())

        def list_tables(self) -> list[str]:
            return list(TABLE_TO_ENTITY)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            del table_options
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            del table_options
            self._validate_table(table_name)
            return {
                "primary_keys": ["realm_id", "id"],
                "cursor_field": CURSOR_FIELD,
                "ingestion_type": (
                    "cdc_with_deletes" if table_name in DELETABLE_TABLES else "cdc"
                ),
            }

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            page_size = int(table_options.get("page_size", str(DEFAULT_PAGE_SIZE)))
            if not 1 <= page_size <= 1000:
                raise ValueError("page_size must be between 1 and 1000")

            return self._read_incrementally(
                table_name,
                start_offset,
                table_options,
                page_size=page_size,
            )

        def _read_incrementally(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
            *,
            page_size: int,
        ) -> tuple[Iterator[dict], dict]:
            cursor = _parse_offset(
                start_offset,
                expected_realm_id=self._realm_id,
                expected_table_name=table_name,
                expected_flow="updates",
            )
            init_dt = _parse_qbo_datetime(self._init_ts)
            entity = TABLE_TO_ENTITY[table_name]

            # First call: emit the complete snapshot, but checkpoint the time at
            # which this reader was initialized. Changes racing with the snapshot
            # are replayed by the overlap on the next trigger.
            if cursor is None:
                where_clause = "Active IN (true, false)" if table_name in LIST_TABLES else None
                records = (
                    _normalize_cdc_entity(table_name, row, realm_id=self._realm_id)
                    for row in self._client.iter_entity(
                        entity,
                        page_size=page_size,
                        where_clause=where_clause,
                    )
                )
                return records, _offset(
                    self._init_ts,
                    realm_id=self._realm_id,
                    table_name=table_name,
                    flow="updates",
                )

            cursor_dt = _parse_qbo_datetime(cursor)
            if cursor_dt >= init_dt:
                return iter([]), start_offset

            overlap_seconds = _bounded_int_option(
                table_options,
                "incremental_overlap_seconds",
                default=DEFAULT_INCREMENTAL_OVERLAP_SECONDS,
                minimum=0,
                maximum=3600,
            )
            max_window_seconds = _bounded_int_option(
                table_options,
                "max_incremental_window_seconds",
                default=DEFAULT_MAX_INCREMENTAL_WINDOW_SECONDS,
                minimum=60,
                maximum=604800,
            )
            lower_dt = cursor_dt - timedelta(seconds=overlap_seconds)
            upper_dt = min(
                cursor_dt + timedelta(seconds=max_window_seconds),
                init_dt,
            )
            lower = _format_qbo_datetime(lower_dt)
            upper = _format_qbo_datetime(upper_dt)
            predicates = []
            if table_name in LIST_TABLES:
                predicates.append("Active IN (true, false)")
            predicates.extend(
                [
                    f"MetaData.LastUpdatedTime >= '{lower}'",
                    f"MetaData.LastUpdatedTime <= '{upper}'",
                ]
            )
            where_clause = " AND ".join(predicates)
            records = (
                _normalize_cdc_entity(table_name, row, realm_id=self._realm_id)
                for row in self._client.iter_entity(
                    entity,
                    page_size=page_size,
                    where_clause=where_clause,
                )
            )
            return records, _offset(
                upper,
                realm_id=self._realm_id,
                table_name=table_name,
                flow="updates",
            )

        def read_table_deletes(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Read hard-delete tombstones for QuickBooks transaction entities."""
            self._validate_table(table_name)
            if table_name not in DELETABLE_TABLES:
                raise ValueError(
                    f"QuickBooks {TABLE_TO_ENTITY[table_name]} is inactivated, not hard-deleted"
                )

            cursor = _parse_offset(
                start_offset,
                expected_realm_id=self._realm_id,
                expected_table_name=table_name,
                expected_flow="deletes",
            )
            init_dt = _parse_qbo_datetime(self._init_ts)
            if cursor is not None and _parse_qbo_datetime(cursor) >= init_dt:
                return iter([]), start_offset

            if cursor is None:
                lookback_seconds = _bounded_int_option(
                    table_options,
                    "initial_delete_lookback_seconds",
                    default=DEFAULT_INITIAL_DELETE_LOOKBACK_SECONDS,
                    minimum=0,
                    maximum=86400,
                )
                lower_dt = init_dt - timedelta(seconds=lookback_seconds)
            else:
                cursor_dt = _parse_qbo_datetime(cursor)
                overlap_seconds = _bounded_int_option(
                    table_options,
                    "delete_overlap_seconds",
                    default=DEFAULT_DELETE_OVERLAP_SECONDS,
                    minimum=0,
                    maximum=3600,
                )
                lower_dt = cursor_dt - timedelta(seconds=overlap_seconds)
                if init_dt - lower_dt > timedelta(seconds=MAX_CDC_LOOKBACK_SECONDS):
                    raise RuntimeError(
                        "QuickBooks CDC can only recover deletes from the previous 30 days; "
                        "the delete checkpoint was not advanced. Perform a full reconciliation."
                    )

            changed_since = _format_qbo_datetime(lower_dt)
            entity = TABLE_TO_ENTITY[table_name]
            changes, response_time = self._client.get_entity_changes(
                entity,
                changed_since=changed_since,
            )
            response_dt = _parse_qbo_datetime(response_time)
            if response_dt < lower_dt:
                raise RuntimeError("QuickBooks CDC server time precedes changedSince")

            tombstones = (
                _normalize_delete_entity(table_name, row, realm_id=self._realm_id)
                for row in changes
                if str(row.get("status", "")).lower() == "deleted"
            )
            return tombstones, _offset(
                response_time,
                realm_id=self._realm_id,
                table_name=table_name,
                flow="deletes",
            )

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLE_TO_ENTITY:
                raise ValueError(
                    f"Unsupported QuickBooks table '{table_name}'. "
                    f"Supported tables: {self.list_tables()}"
                )


    def _normalize_entity(table_name: str, row: dict, *, realm_id: str) -> dict:
        entity_id = row.get("Id")
        if entity_id in {None, ""}:
            raise RuntimeError("QuickBooks entity is missing Id")
        metadata = row.get("MetaData") if isinstance(row.get("MetaData"), dict) else {}
        common = {
            "realm_id": realm_id,
            "id": str(entity_id),
            "sync_token": _optional_string(row.get("SyncToken")),
            "created_at": _optional_datetime(metadata.get("CreateTime")),
            "last_updated_at": _optional_datetime(metadata.get("LastUpdatedTime")),
            "raw_json": json.dumps(row, separators=(",", ":"), sort_keys=True),
        }
        normalizers = {
            "customers": _normalize_customer,
            "vendors": _normalize_vendor,
            "accounts": _normalize_account,
            "items": _normalize_item,
            "invoices": _normalize_invoice,
            "bills": _normalize_bill,
        }
        return common | normalizers[table_name](row)


    def _normalize_cdc_entity(table_name: str, row: dict, *, realm_id: str) -> dict:
        record = _normalize_entity(table_name, row, realm_id=realm_id)
        if record[CURSOR_FIELD] is None:
            entity = TABLE_TO_ENTITY[table_name]
            raise RuntimeError(f"QuickBooks {entity} is missing MetaData.LastUpdatedTime")
        return record


    def _normalize_delete_entity(table_name: str, row: dict, *, realm_id: str) -> dict:
        """Build a schema-complete tombstone from QuickBooks' minimal delete body."""
        entity_id = row.get("Id")
        if entity_id in {None, ""}:
            raise RuntimeError("QuickBooks deleted entity is missing Id")
        metadata = row.get("MetaData") if isinstance(row.get("MetaData"), dict) else {}
        last_updated_at = _optional_datetime(metadata.get("LastUpdatedTime"))
        if last_updated_at is None:
            raise RuntimeError("QuickBooks deleted entity is missing MetaData.LastUpdatedTime")

        tombstone = {field.name: None for field in TABLE_SCHEMAS[table_name].fields}
        tombstone.update(
            {
                "realm_id": realm_id,
                "id": str(entity_id),
                "sync_token": _optional_string(row.get("SyncToken")),
                CURSOR_FIELD: last_updated_at,
                "raw_json": json.dumps(row, separators=(",", ":"), sort_keys=True),
            }
        )
        return tombstone


    def _normalize_customer(row: dict) -> dict:
        return _party_fields(row) | {
            "balance": _optional_decimal(row.get("Balance")),
            "currency_ref": _reference_value(row.get("CurrencyRef")),
            "active": _optional_bool(row.get("Active")),
        }


    def _normalize_vendor(row: dict) -> dict:
        return _party_fields(row) | {
            "balance": _optional_decimal(row.get("Balance")),
            "vendor_1099": _optional_bool(row.get("Vendor1099")),
            "currency_ref": _reference_value(row.get("CurrencyRef")),
            "active": _optional_bool(row.get("Active")),
        }


    def _party_fields(row: dict) -> dict:
        return {
            "display_name": _optional_string(row.get("DisplayName")),
            "company_name": _optional_string(row.get("CompanyName")),
            "given_name": _optional_string(row.get("GivenName")),
            "family_name": _optional_string(row.get("FamilyName")),
            "primary_email": _nested_string(row, "PrimaryEmailAddr", "Address"),
            "primary_phone": _nested_string(row, "PrimaryPhone", "FreeFormNumber"),
        }


    def _normalize_account(row: dict) -> dict:
        return {
            "name": _optional_string(row.get("Name")),
            "fully_qualified_name": _optional_string(row.get("FullyQualifiedName")),
            "account_type": _optional_string(row.get("AccountType")),
            "account_sub_type": _optional_string(row.get("AccountSubType")),
            "classification": _optional_string(row.get("Classification")),
            "current_balance": _optional_decimal(row.get("CurrentBalance")),
            "currency_ref": _reference_value(row.get("CurrencyRef")),
            "active": _optional_bool(row.get("Active")),
        }


    def _normalize_item(row: dict) -> dict:
        return {
            "name": _optional_string(row.get("Name")),
            "fully_qualified_name": _optional_string(row.get("FullyQualifiedName")),
            "item_type": _optional_string(row.get("Type")),
            "description": _optional_string(row.get("Description")),
            "unit_price": _optional_decimal(row.get("UnitPrice")),
            "purchase_cost": _optional_decimal(row.get("PurchaseCost")),
            "quantity_on_hand": _optional_decimal(row.get("QtyOnHand")),
            "income_account_ref": _reference_value(row.get("IncomeAccountRef")),
            "expense_account_ref": _reference_value(row.get("ExpenseAccountRef")),
            "asset_account_ref": _reference_value(row.get("AssetAccountRef")),
            "active": _optional_bool(row.get("Active")),
        }


    def _normalize_invoice(row: dict) -> dict:
        return _transaction_fields(row) | {
            "customer_ref": _reference_value(row.get("CustomerRef")),
            "email_status": _optional_string(row.get("EmailStatus")),
            "print_status": _optional_string(row.get("PrintStatus")),
        }


    def _normalize_bill(row: dict) -> dict:
        return _transaction_fields(row) | {
            "vendor_ref": _reference_value(row.get("VendorRef")),
            "ap_account_ref": _reference_value(row.get("APAccountRef")),
        }


    def _transaction_fields(row: dict) -> dict:
        lines = row.get("Line")
        return {
            "doc_number": _optional_string(row.get("DocNumber")),
            "txn_date": _optional_date(row.get("TxnDate")),
            "due_date": _optional_date(row.get("DueDate")),
            "total_amount": _optional_decimal(row.get("TotalAmt")),
            "balance": _optional_decimal(row.get("Balance")),
            "currency_ref": _reference_value(row.get("CurrencyRef")),
            "line_json": (
                json.dumps(lines, separators=(",", ":"), sort_keys=True)
                if isinstance(lines, list)
                else None
            ),
        }


    def _optional_string(value: object) -> str | None:
        if value in {None, ""}:
            return None
        return str(value)


    def _optional_decimal(value: object) -> Decimal | None:
        if value in {None, ""}:
            return None
        try:
            return Decimal(str(value))
        except (ArithmeticError, ValueError) as exc:
            raise RuntimeError(f"Invalid QuickBooks decimal value: {value!r}") from exc


    def _optional_datetime(value: object) -> datetime | None:
        if value in {None, ""}:
            return None
        try:
            return datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        except ValueError as exc:
            raise RuntimeError(f"Invalid QuickBooks timestamp: {value!r}") from exc


    def _optional_date(value: object) -> str | None:
        if value in {None, ""}:
            return None
        try:
            return datetime.strptime(str(value), "%Y-%m-%d").date().isoformat()
        except ValueError as exc:
            raise RuntimeError(f"Invalid QuickBooks date: {value!r}") from exc


    def _optional_bool(value: object) -> bool | None:
        return value if isinstance(value, bool) else None


    def _nested_string(row: dict, parent: str, child: str) -> str | None:
        value = row.get(parent)
        if not isinstance(value, dict):
            return None
        return _optional_string(value.get(child))


    def _reference_value(value: object) -> str | None:
        if not isinstance(value, dict):
            return None
        return _optional_string(value.get("value"))


    def _retry_after_seconds(value: str | None) -> float | None:
        if not value:
            return None
        try:
            return max(0.0, float(value))
        except ValueError:
            try:
                target = parsedate_to_datetime(value)
            except (TypeError, ValueError):
                return None
            now = datetime.now(target.tzinfo)
            return max(0.0, (target - now).total_seconds())


    def _utc_now() -> datetime:
        return datetime.now(timezone.utc)


    def _format_qbo_datetime(value: datetime) -> str:
        if value.tzinfo is None:
            raise ValueError("QuickBooks cursor datetime must include a timezone")
        utc_value = value.astimezone(timezone.utc)
        return utc_value.isoformat(timespec="seconds").replace("+00:00", "Z")


    def _parse_qbo_datetime(value: str) -> datetime:
        try:
            parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        except (AttributeError, ValueError) as exc:
            raise ValueError(f"Invalid QuickBooks cursor timestamp: {value!r}") from exc
        if parsed.tzinfo is None:
            raise ValueError(f"QuickBooks cursor timestamp must include a timezone: {value!r}")
        return parsed.astimezone(timezone.utc)


    def _offset(
        updated_through: str,
        *,
        realm_id: str,
        table_name: str,
        flow: str,
    ) -> dict:
        return {
            OFFSET_VERSION_KEY: OFFSET_VERSION,
            OFFSET_REALM_KEY: realm_id,
            OFFSET_TABLE_KEY: table_name,
            OFFSET_FLOW_KEY: flow,
            OFFSET_CURSOR_KEY: updated_through,
        }


    def _parse_offset(
        start_offset: dict,
        *,
        expected_realm_id: str,
        expected_table_name: str,
        expected_flow: str,
    ) -> str | None:
        if not start_offset:
            return None
        if start_offset.get(OFFSET_VERSION_KEY) != OFFSET_VERSION:
            raise ValueError(
                f"Unsupported QuickBooks offset version: {start_offset.get(OFFSET_VERSION_KEY)!r}"
            )
        realm_id = start_offset.get(OFFSET_REALM_KEY)
        if realm_id != expected_realm_id:
            raise ValueError(
                "QuickBooks offset realm_id does not match the configured Unity Catalog "
                "connection; reset the pipeline checkpoint only after validating the tenant"
            )
        if start_offset.get(OFFSET_TABLE_KEY) != expected_table_name:
            raise ValueError(
                "QuickBooks offset table_name does not match the requested table; "
                "check the pipeline's checkpoint isolation"
            )
        if start_offset.get(OFFSET_FLOW_KEY) != expected_flow:
            raise ValueError(
                "QuickBooks offset flow does not match the requested update/delete flow; "
                "check the pipeline's checkpoint isolation"
            )
        cursor = start_offset.get(OFFSET_CURSOR_KEY)
        if not isinstance(cursor, str) or not cursor:
            raise ValueError(f"QuickBooks offset requires non-empty '{OFFSET_CURSOR_KEY}'")
        _parse_qbo_datetime(cursor)
        return cursor


    def _bounded_int_option(
        options: dict[str, str],
        name: str,
        *,
        default: int,
        minimum: int,
        maximum: int,
    ) -> int:
        try:
            value = int(options.get(name, str(default)))
        except (TypeError, ValueError) as exc:
            raise ValueError(f"{name} must be an integer") from exc
        if not minimum <= value <= maximum:
            raise ValueError(f"{name} must be between {minimum} and {maximum}")
        return value


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = QuickBooksLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
