# ==============================================================================
# Merged Lakeflow Source: wordpress
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/wordpress/wordpress_schemas.py
    ########################################################

    def _rendered_struct() -> StructType:
        """``{ "rendered": "<html>" }`` — guid / title / description / caption."""
        return StructType([StructField("rendered", StringType(), nullable=True)])


    def _rendered_protected_struct() -> StructType:
        """``{ "rendered": "<html>", "protected": bool }`` — content / excerpt."""
        return StructType(
            [
                StructField("rendered", StringType(), nullable=True),
                StructField("protected", BooleanType(), nullable=True),
            ]
        )


    def _avatar_urls_struct() -> StructType:
        """Avatar/gravatar URLs keyed by pixel size (24 / 48 / 96)."""
        return StructType(
            [
                StructField("24", StringType(), nullable=True),
                StructField("48", StringType(), nullable=True),
                StructField("96", StringType(), nullable=True),
            ]
        )


    def _media_details_struct() -> StructType:
        """Shallow subset of ``media_details`` common to image attachments.

        The full object varies by ``media_type`` (image vs file) and includes a
        per-size ``sizes`` map with install-specific keys, so only the stable
        scalar fields are modelled here.
        """
        return StructType(
            [
                StructField("width", LongType(), nullable=True),
                StructField("height", LongType(), nullable=True),
                StructField("file", StringType(), nullable=True),
                StructField("filesize", LongType(), nullable=True),
            ]
        )


    # --------------------------------------------------------------------------- #
    # Table schemas
    # --------------------------------------------------------------------------- #

    _POSTS_SCHEMA = StructType(
        [
            StructField("id", LongType(), nullable=False),
            StructField("date", TimestampType(), nullable=True),
            StructField("date_gmt", TimestampType(), nullable=True),
            StructField("modified", TimestampType(), nullable=True),
            StructField("modified_gmt", TimestampType(), nullable=True),
            StructField("guid", _rendered_struct(), nullable=True),
            StructField("slug", StringType(), nullable=True),
            StructField("status", StringType(), nullable=True),
            StructField("type", StringType(), nullable=True),
            StructField("link", StringType(), nullable=True),
            StructField("title", _rendered_struct(), nullable=True),
            StructField("content", _rendered_protected_struct(), nullable=True),
            StructField("excerpt", _rendered_protected_struct(), nullable=True),
            StructField("author", LongType(), nullable=True),
            StructField("featured_media", LongType(), nullable=True),
            StructField("comment_status", StringType(), nullable=True),
            StructField("ping_status", StringType(), nullable=True),
            StructField("sticky", BooleanType(), nullable=True),
            StructField("template", StringType(), nullable=True),
            StructField("format", StringType(), nullable=True),
            StructField("categories", ArrayType(LongType()), nullable=True),
            StructField("tags", ArrayType(LongType()), nullable=True),
        ]
    )

    _PAGES_SCHEMA = StructType(
        [
            StructField("id", LongType(), nullable=False),
            StructField("date", TimestampType(), nullable=True),
            StructField("date_gmt", TimestampType(), nullable=True),
            StructField("modified", TimestampType(), nullable=True),
            StructField("modified_gmt", TimestampType(), nullable=True),
            StructField("guid", _rendered_struct(), nullable=True),
            StructField("slug", StringType(), nullable=True),
            StructField("status", StringType(), nullable=True),
            StructField("type", StringType(), nullable=True),
            StructField("link", StringType(), nullable=True),
            StructField("title", _rendered_struct(), nullable=True),
            StructField("content", _rendered_protected_struct(), nullable=True),
            StructField("excerpt", _rendered_protected_struct(), nullable=True),
            StructField("author", LongType(), nullable=True),
            StructField("featured_media", LongType(), nullable=True),
            StructField("comment_status", StringType(), nullable=True),
            StructField("ping_status", StringType(), nullable=True),
            StructField("template", StringType(), nullable=True),
            StructField("parent", LongType(), nullable=True),
            StructField("menu_order", LongType(), nullable=True),
        ]
    )

    _MEDIA_SCHEMA = StructType(
        [
            StructField("id", LongType(), nullable=False),
            StructField("date", TimestampType(), nullable=True),
            StructField("date_gmt", TimestampType(), nullable=True),
            StructField("modified", TimestampType(), nullable=True),
            StructField("modified_gmt", TimestampType(), nullable=True),
            StructField("guid", _rendered_struct(), nullable=True),
            StructField("slug", StringType(), nullable=True),
            StructField("status", StringType(), nullable=True),
            StructField("type", StringType(), nullable=True),
            StructField("link", StringType(), nullable=True),
            StructField("title", _rendered_struct(), nullable=True),
            StructField("author", LongType(), nullable=True),
            StructField("comment_status", StringType(), nullable=True),
            StructField("ping_status", StringType(), nullable=True),
            StructField("template", StringType(), nullable=True),
            StructField("description", _rendered_struct(), nullable=True),
            StructField("caption", _rendered_struct(), nullable=True),
            StructField("alt_text", StringType(), nullable=True),
            StructField("media_type", StringType(), nullable=True),
            StructField("mime_type", StringType(), nullable=True),
            StructField("media_details", _media_details_struct(), nullable=True),
            StructField("post", LongType(), nullable=True),
            StructField("source_url", StringType(), nullable=True),
        ]
    )

    _COMMENTS_SCHEMA = StructType(
        [
            StructField("id", LongType(), nullable=False),
            StructField("post", LongType(), nullable=True),
            StructField("parent", LongType(), nullable=True),
            StructField("author", LongType(), nullable=True),
            StructField("author_name", StringType(), nullable=True),
            StructField("author_url", StringType(), nullable=True),
            StructField("date", TimestampType(), nullable=True),
            StructField("date_gmt", TimestampType(), nullable=True),
            StructField("content", _rendered_struct(), nullable=True),
            StructField("link", StringType(), nullable=True),
            StructField("status", StringType(), nullable=True),
            StructField("type", StringType(), nullable=True),
            StructField("author_avatar_urls", _avatar_urls_struct(), nullable=True),
        ]
    )

    _CATEGORIES_SCHEMA = StructType(
        [
            StructField("id", LongType(), nullable=False),
            StructField("count", LongType(), nullable=True),
            StructField("description", StringType(), nullable=True),
            StructField("link", StringType(), nullable=True),
            StructField("name", StringType(), nullable=True),
            StructField("slug", StringType(), nullable=True),
            StructField("taxonomy", StringType(), nullable=True),
            StructField("parent", LongType(), nullable=True),
        ]
    )

    _TAGS_SCHEMA = StructType(
        [
            StructField("id", LongType(), nullable=False),
            StructField("count", LongType(), nullable=True),
            StructField("description", StringType(), nullable=True),
            StructField("link", StringType(), nullable=True),
            StructField("name", StringType(), nullable=True),
            StructField("slug", StringType(), nullable=True),
            StructField("taxonomy", StringType(), nullable=True),
        ]
    )

    _USERS_SCHEMA = StructType(
        [
            StructField("id", LongType(), nullable=False),
            StructField("name", StringType(), nullable=True),
            StructField("url", StringType(), nullable=True),
            StructField("description", StringType(), nullable=True),
            StructField("link", StringType(), nullable=True),
            StructField("slug", StringType(), nullable=True),
            StructField("avatar_urls", _avatar_urls_struct(), nullable=True),
        ]
    )

    _TAXONOMIES_SCHEMA = StructType(
        [
            StructField("name", StringType(), nullable=True),
            StructField("slug", StringType(), nullable=False),
            StructField("description", StringType(), nullable=True),
            StructField("types", ArrayType(StringType()), nullable=True),
            StructField("hierarchical", BooleanType(), nullable=True),
            StructField("rest_base", StringType(), nullable=True),
        ]
    )

    TABLE_SCHEMAS: dict[str, StructType] = {
        "posts": _POSTS_SCHEMA,
        "pages": _PAGES_SCHEMA,
        "media": _MEDIA_SCHEMA,
        "comments": _COMMENTS_SCHEMA,
        "categories": _CATEGORIES_SCHEMA,
        "tags": _TAGS_SCHEMA,
        "users": _USERS_SCHEMA,
        "taxonomies": _TAXONOMIES_SCHEMA,
    }

    # --------------------------------------------------------------------------- #
    # Per-table configuration
    # --------------------------------------------------------------------------- #
    #
    # ``endpoint``       — path segment under ``/wp-json/wp/v2/``.
    # ``ingestion``      — snapshot / cdc / append.
    # ``cursor``         — record field holding the incremental watermark (UTC).
    # ``after_param`` /  — WordPress query params bounding the cursor range.
    #   ``before_param``
    # ``primary_keys``   — used for merge + corpus PK uniqueness.
    # ``partitioned``    — True → partitioned streaming path; False → snapshot via
    #                      ``read_table`` (simpleStreamReader).
    # ``dict_shaped``    — response is a dict keyed by slug rather than an array.
    # ``sort_field``     — WordPress ``orderby`` value for a stable ascending read.

    TABLE_CONFIG: dict[str, dict] = {
        "posts": {
            "endpoint": "posts",
            "ingestion": "cdc",
            "cursor": "modified_gmt",
            "after_param": "modified_after",
            "before_param": "modified_before",
            "primary_keys": ["id"],
            "partitioned": True,
            "sort_field": "modified",
        },
        "pages": {
            "endpoint": "pages",
            "ingestion": "cdc",
            "cursor": "modified_gmt",
            "after_param": "modified_after",
            "before_param": "modified_before",
            "primary_keys": ["id"],
            "partitioned": True,
            "sort_field": "modified",
        },
        "media": {
            "endpoint": "media",
            "ingestion": "cdc",
            "cursor": "modified_gmt",
            "after_param": "modified_after",
            "before_param": "modified_before",
            "primary_keys": ["id"],
            "partitioned": True,
            "sort_field": "modified",
        },
        "comments": {
            "endpoint": "comments",
            "ingestion": "append",
            "cursor": "date_gmt",
            "after_param": "after",
            "before_param": "before",
            "primary_keys": ["id"],
            "partitioned": True,
            "sort_field": "date",
        },
        "categories": {
            "endpoint": "categories",
            "ingestion": "snapshot",
            "cursor": None,
            "primary_keys": ["id"],
            "partitioned": False,
        },
        "tags": {
            "endpoint": "tags",
            "ingestion": "snapshot",
            "cursor": None,
            "primary_keys": ["id"],
            "partitioned": False,
        },
        "users": {
            "endpoint": "users",
            "ingestion": "snapshot",
            "cursor": None,
            "primary_keys": ["id"],
            "partitioned": False,
        },
        "taxonomies": {
            "endpoint": "taxonomies",
            "ingestion": "snapshot",
            "cursor": None,
            "primary_keys": ["slug"],
            "partitioned": False,
            "dict_shaped": True,
        },
    }

    SUPPORTED_TABLES: list[str] = list(TABLE_CONFIG.keys())


    def build_metadata(table_name: str) -> dict:
        """Return LakeflowConnect metadata for ``table_name``."""
        cfg = TABLE_CONFIG[table_name]
        return {
            "primary_keys": list(cfg["primary_keys"]),
            "cursor_field": cfg.get("cursor"),
            "ingestion_type": cfg["ingestion"],
        }


    ########################################################
    # src/databricks/labs/community_connector/sources/wordpress/wordpress_utils.py
    ########################################################

    MAX_PER_PAGE = 100
    DEFAULT_PER_PAGE = 100

    # Requests that should be retried with exponential backoff.
    RETRIABLE_STATUS_CODES = {429, 500, 502, 503}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry

    # Credential / capability errors — fail fast, do not retry.
    FATAL_STATUS_CODES = {401, 403}

    # WordPress error code returned (with HTTP 400) when a requested ``page`` is
    # beyond ``X-WP-TotalPages``.  Treated as end-of-pagination, not a failure.
    # WordPress emits per-resource variants (rest_post_invalid_page_number,
    # rest_comment_invalid_page_number, ...), all ending in this suffix.
    INVALID_PAGE_SUFFIX = "invalid_page_number"

    TS_FMT = "%Y-%m-%dT%H:%M:%SZ"


    class WordPressError(RuntimeError):
        """Raised for non-retriable, non-terminal WordPress API errors."""


    def build_session(username: str, application_password: str) -> requests.Session:
        """Create a ``requests.Session`` pre-configured for WordPress Basic Auth.

        WordPress strips spaces from Application Passwords internally, so the
        space-grouped secret is sent verbatim.
        """
        session = requests.Session()
        session.auth = (username, application_password)
        session.headers.update({"Accept": "application/json"})
        return session


    def _is_invalid_page_error(response: requests.Response) -> bool:
        """Return True when the response is a ``*_invalid_page_number`` 400."""
        if response.status_code != 400:
            return False
        try:
            code = (response.json() or {}).get("code", "")
        except ValueError:
            return False
        return isinstance(code, str) and code.endswith(INVALID_PAGE_SUFFIX)


    def _error_message(response: requests.Response) -> str:
        try:
            body = response.json()
        except ValueError:
            body = response.text
        return f"HTTP {response.status_code}: {body}"


    def request_with_retry(
        session: requests.Session,
        url: str,
        params: dict[str, Any] | None,
        timeout: int = 30,
    ) -> requests.Response:
        """Issue a GET, retrying 429/5xx with exponential backoff.

        Honors the ``Retry-After`` header on 429 when present.  Fails fast on
        401/403 (credential / capability problems).  ``*_invalid_page_number``
        400 responses are returned as-is so the caller can treat them as
        end-of-pagination.
        """
        backoff = INITIAL_BACKOFF
        response: requests.Response | None = None
        for attempt in range(MAX_RETRIES):
            response = session.get(url, params=params, timeout=timeout)

            if response.status_code in FATAL_STATUS_CODES:
                raise WordPressError(
                    "WordPress rejected the request (check the Application Password "
                    f"and the user's capabilities). {_error_message(response)}"
                )

            if response.status_code not in RETRIABLE_STATUS_CODES:
                return response

            if attempt < MAX_RETRIES - 1:
                wait = backoff
                retry_after = response.headers.get("Retry-After")
                if retry_after:
                    try:
                        wait = max(wait, float(retry_after))
                    except (TypeError, ValueError):
                        pass
                time.sleep(wait)
                backoff *= 2

        # Exhausted retries — surface the last response.
        raise WordPressError(
            f"WordPress API still failing after {MAX_RETRIES} attempts. "
            f"{_error_message(response) if response is not None else ''}"
        )


    def paginate(
        session: requests.Session,
        url: str,
        params: dict[str, Any],
        *,
        per_page: int = DEFAULT_PER_PAGE,
        max_records: int | None = None,
        timeout: int = 30,
    ) -> Iterator[dict]:
        """Yield every record across pages for a WordPress list endpoint.

        Pagination stops when:
          * a page returns an ``*_invalid_page_number`` 400 (past the last page),
          * the returned array is empty or shorter than ``per_page``, or
          * ``max_records`` records have been yielded.

        Header-based termination (``X-WP-TotalPages``) is intentionally *not*
        relied upon: the count-and-short-page approach works identically against
        the live API and the offline simulator (which serves no WP headers).
        """
        page = 1
        yielded = 0
        query = dict(params)
        query["per_page"] = per_page

        while True:
            query["page"] = page
            response = request_with_retry(session, url, query, timeout=timeout)

            if _is_invalid_page_error(response):
                return
            if response.status_code != 200:
                raise WordPressError(_error_message(response))

            batch = response.json()
            if not isinstance(batch, list):
                raise WordPressError(f"Expected a JSON array from {url!r}, got {type(batch).__name__}")
            if not batch:
                return

            for record in batch:
                yield record
                yielded += 1
                if max_records is not None and yielded >= max_records:
                    return

            if len(batch) < per_page:
                return
            page += 1


    # --------------------------------------------------------------------------- #
    # Timestamp helpers (UTC, second precision, lexicographically comparable)
    # --------------------------------------------------------------------------- #


    def now_utc_iso() -> str:
        """Current wall-clock time as ``YYYY-MM-DDTHH:MM:SSZ``."""
        return datetime.now(timezone.utc).strftime(TS_FMT)


    def parse_ts(value: str | None) -> datetime | None:
        """Parse an ISO 8601 timestamp to an aware datetime, or None on failure."""
        if not value:
            return None
        try:
            dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
        except (TypeError, ValueError):
            return None
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt


    def normalize_ts(value: str | None) -> str | None:
        """Normalise a timestamp to ``TS_FMT`` so string compares are consistent."""
        dt = parse_ts(value)
        if dt is None:
            return None
        return dt.astimezone(timezone.utc).strftime(TS_FMT)


    def add_seconds(value: str, seconds: int) -> str:
        """Return ``value`` shifted forward by ``seconds`` in ``TS_FMT``."""
        dt = parse_ts(value)
        if dt is None:
            raise ValueError(f"{value!r} is not a valid ISO 8601 timestamp")
        return (dt + timedelta(seconds=seconds)).astimezone(timezone.utc).strftime(TS_FMT)


    ########################################################
    # src/databricks/labs/community_connector/sources/wordpress/wordpress.py
    ########################################################

    DEFAULT_START_TIMESTAMP = "1970-01-01T00:00:00Z"
    DEFAULT_NUM_PARTITIONS = 4
    DEFAULT_LOOKBACK_SECONDS = 0


    class WordPressLakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """Lakeflow connector for the WordPress REST API (``wp/v2``)."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)

            base_url = options.get("base_url")
            username = options.get("username")
            application_password = options.get("application_password")

            if not base_url:
                raise ValueError("WordPress connector requires 'base_url' in options")
            if not username:
                raise ValueError("WordPress connector requires 'username' in options")
            if not application_password:
                raise ValueError("WordPress connector requires 'application_password' in options")

            # Site root, e.g. https://example.com — the wp/v2 path is appended per
            # request.  Trailing slashes / an accidental /wp-json suffix are trimmed.
            root = base_url.rstrip("/")
            if root.endswith("/wp-json"):
                root = root[: -len("/wp-json")]
            self._api_base = f"{root}/wp-json/wp/v2"

            self._username = username
            self._application_password = application_password
            self._session = wp.build_session(username, application_password)

            # Freeze the upper bound at init time so latest_offset returns a stable
            # value across every micro-batch in a single Trigger.AvailableNow run.
            # Data modified after this instant is picked up by the next trigger,
            # which constructs a fresh connector with a newer init time.
            self._init_time = wp.now_utc_iso()

        # ------------------------------------------------------------------ #
        # Interface: discovery / schema / metadata
        # ------------------------------------------------------------------ #

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            return build_metadata(table_name)

        # ------------------------------------------------------------------ #
        # Interface: non-partitioned reads (snapshot tables via simpleStreamReader)
        # ------------------------------------------------------------------ #

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            cfg = TABLE_CONFIG[table_name]

            if cfg["partitioned"]:
                raise ValueError(
                    f"Table '{table_name}' uses the partitioned streaming path; "
                    "read_table is not used for it."
                )

            # Snapshot tables: full read, no checkpointable offset.
            if cfg.get("dict_shaped"):
                return iter(self._read_dict_shaped(table_name)), {}
            return iter(self._read_snapshot_list(table_name, table_options)), {}

        # ------------------------------------------------------------------ #
        # SupportsPartitionedStream
        # ------------------------------------------------------------------ #

        def is_partitioned(self, table_name: str) -> bool:
            self._validate_table(table_name)
            return bool(TABLE_CONFIG[table_name]["partitioned"])

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the high-water mark for the table, capped at init time.

            Metadata-only: no records are read here.  When ``window_seconds`` is
            set, the offset advances by one window per micro-batch (bounding batch
            size); otherwise it jumps straight to the init-time cap.  In both cases
            the value stabilises once the stream catches up, so the trigger
            terminates.
            """
            self._validate_table(table_name)
            window_seconds = self._int_option(table_options, "window_seconds", 0)
            if window_seconds > 0:
                current = (start_offset or {}).get("cursor")
                if not current:
                    current = self._resolve_start(table_options)
                next_end = wp.add_seconds(current, window_seconds)
                return {"cursor": min(next_end, self._init_time)}
            return {"cursor": self._init_time}

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> list[dict]:
            """Split the ``(start, end]`` cursor range into contiguous time windows."""
            self._validate_table(table_name)

            start_cursor = (start_offset or {}).get("cursor") if start_offset else None
            if not start_cursor:
                start_cursor = self._resolve_start(table_options)

            if end_offset is not None:
                end_cursor = end_offset.get("cursor") or self._init_time
            else:
                # Batch mode: cover the whole table up to the init-time cap.
                end_cursor = self._init_time

            # Apply the lookback only once, at the lower bound of the range, to
            # catch records edited during a prior window.  The stored cursor is
            # never widened by this.
            lookback = self._int_option(table_options, "lookback_seconds", DEFAULT_LOOKBACK_SECONDS)
            if lookback > 0 and start_cursor != DEFAULT_START_TIMESTAMP:
                start_cursor = wp.add_seconds(start_cursor, -lookback)

            start_dt = wp.parse_ts(start_cursor)
            end_dt = wp.parse_ts(end_cursor)
            if start_dt is None or end_dt is None or start_dt >= end_dt:
                return []

            num_partitions = max(
                1, self._int_option(table_options, "num_partitions", DEFAULT_NUM_PARTITIONS)
            )
            total_seconds = (end_dt - start_dt).total_seconds()
            step = total_seconds / num_partitions

            partitions: list[dict] = []
            for i in range(num_partitions):
                since = wp.add_seconds(start_cursor, int(round(step * i)))
                if i == num_partitions - 1:
                    until = end_cursor
                else:
                    until = wp.add_seconds(start_cursor, int(round(step * (i + 1))))
                if wp.parse_ts(since) >= wp.parse_ts(until):
                    continue
                partitions.append({"since": since, "until": until})
            return partitions

        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Fetch one time window on an executor.

            Self-contained: rebuilds its own session from ``self.options`` rather
            than relying on any driver-side state.
            """
            self._validate_table(table_name)
            cfg = TABLE_CONFIG[table_name]

            session = wp.build_session(self._username, self._application_password)
            url = f"{self._api_base}/{cfg['endpoint']}"

            # Lower bound exclusive (``after``); upper bound made inclusive at
            # second precision via ``before = until + 1s`` so a record landing on
            # an interior boundary belongs to exactly one window.
            params: dict[str, Any] = {
                "orderby": cfg["sort_field"],
                "order": "asc",
            }
            params[cfg["after_param"]] = partition["since"]
            params[cfg["before_param"]] = wp.add_seconds(partition["until"], 1)

            per_page = self._int_option(table_options, "per_page", wp.DEFAULT_PER_PAGE)
            per_page = max(1, min(per_page, wp.MAX_PER_PAGE))

            return self._emit(wp.paginate(session, url, params, per_page=per_page))

        # ------------------------------------------------------------------ #
        # Snapshot readers
        # ------------------------------------------------------------------ #

        def _read_snapshot_list(self, table_name: str, table_options: dict[str, str]) -> Iterator[dict]:
            """Full page-through of a list endpoint (categories / tags / users)."""
            cfg = TABLE_CONFIG[table_name]
            url = f"{self._api_base}/{cfg['endpoint']}"
            per_page = self._int_option(table_options, "per_page", wp.DEFAULT_PER_PAGE)
            per_page = max(1, min(per_page, wp.MAX_PER_PAGE))
            yield from self._emit(wp.paginate(self._session, url, {}, per_page=per_page))

        def _read_dict_shaped(self, table_name: str) -> Iterator[dict]:
            """Read a dict-keyed-by-slug metadata endpoint (``taxonomies``).

            WordPress returns ``{slug: {...}}``; the simulator serves the corpus as
            an array of already-flattened rows.  Both shapes are handled so live
            and simulate modes agree: dict values are promoted to rows with the
            dict key surfaced as ``slug``.
            """
            cfg = TABLE_CONFIG[table_name]
            url = f"{self._api_base}/{cfg['endpoint']}"
            response = wp.request_with_retry(self._session, url, params=None)
            if response.status_code != 200:
                raise wp.WordPressError(f"Failed to read '{table_name}': HTTP {response.status_code}")
            body = response.json()
            if isinstance(body, dict):
                for slug, value in body.items():
                    if isinstance(value, dict):
                        row = dict(value)
                        row.setdefault("slug", slug)
                        yield row
            elif isinstance(body, list):
                for row in body:
                    yield row
            else:
                raise wp.WordPressError(
                    f"Unexpected response shape for '{table_name}': {type(body).__name__}"
                )

        # ------------------------------------------------------------------ #
        # Helpers
        # ------------------------------------------------------------------ #

        @staticmethod
        def _emit(records: Iterator[dict]) -> Iterator[dict]:
            """Pass records through unchanged (raw parsed JSON for the framework)."""
            for record in records:
                yield record

        def _resolve_start(self, table_options: dict[str, str]) -> str:
            """Starting cursor for the first micro-batch of a partitioned table."""
            start = table_options.get("start_timestamp")
            normalized = wp.normalize_ts(start) if start else None
            return normalized or DEFAULT_START_TIMESTAMP

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLE_CONFIG:
                raise ValueError(f"Unsupported table: {table_name!r}. Supported: {SUPPORTED_TABLES}")

        @staticmethod
        def _int_option(table_options: dict[str, str], key: str, default: int) -> int:
            raw = table_options.get(key)
            if raw is None:
                return default
            try:
                return int(raw)
            except (TypeError, ValueError):
                return default


    wp = wordpress_utils


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = WordPressLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
