# ==============================================================================
# Merged Lakeflow Source: hibob
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from __future__ import annotations
from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import copy
import io
import json
import re
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from urllib.parse import quote
import base64
import csv
import logging
import requests
import unicodedata


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/hibob/hibob_schemas.py
    ########################################################

    PRODUCTION_BASE_URL = "https://api.hibob.com/v1"
    SANDBOX_BASE_URL = "https://api.sandbox.hibob.com/v1"

    REQUEST_TIMEOUT_SECONDS = 60
    MAX_RETRIES = 5
    INITIAL_BACKOFF_SECONDS = 1.0
    MAX_BACKOFF_SECONDS = 120.0
    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}

    # Bulk history endpoints: page size bounds (API: 1-200, default 50).
    BULK_DEFAULT_PAGE_SIZE = 200
    BULK_MAX_PAGE_SIZE = 200
    # Max employeeIds per bulk request (API limit).
    BULK_MAX_EMPLOYEE_IDS = 200

    # Time off changes: the API rejects ``since`` older than ~6 months.
    TIME_OFF_DEFAULT_MAX_LOOKBACK_DAYS = 180
    TIME_OFF_DEFAULT_WINDOW_DAYS = 7
    TIME_OFF_DEFAULT_MAX_RECORDS_PER_BATCH = 1000

    # Recursion guard for named-list children.
    NAMED_LIST_MAX_DEPTH = 32

    # Default people-search field list (dot-notation field IDs). Unknown or
    # unpermitted field IDs are silently dropped by the API.
    DEFAULT_EMPLOYEE_FIELDS = [
        "root.id",
        "root.firstName",
        "root.surname",
        "root.email",
        "root.displayName",
        "root.fullName",
        "root.creationDateTime",
        "work.department",
        "work.title",
        "work.startDate",
        "work.manager",
        "work.site",
        "work.siteId",
        "work.reportsTo",
        "internal.status",
        "internal.lifecycleStatus",
        "internal.terminationDate",
        "personal.birthDate",
    ]
    MAX_EMPLOYEE_FIELDS = 400
    HUMAN_READABLE_MODES = {"", "APPEND", "REPLACE"}

    # Bulk history endpoint suffix per table.
    BULK_TABLE_ENDPOINTS = {
        "employee_work_history": "work",
        "employee_employment_history": "employment",
        "employee_lifecycle_history": "lifecycle",
    }

    # Bulk entry fields that hold opaque objects and are serialised to JSON strings.
    BULK_JSON_FIELDS = {"customColumns", "actualWorkingPattern"}

    # ---------------------------------------------------------------------------
    # Reusable struct types
    # ---------------------------------------------------------------------------

    EMPLOYEE_REF_STRUCT = StructType(
        [
            StructField("id", StringType(), True),
            StructField("firstName", StringType(), True),
            StructField("surname", StringType(), True),
            StructField("email", StringType(), True),
            StructField("displayName", StringType(), True),
        ]
    )

    CHANGE_STRUCT = StructType(
        [
            StructField("reason", StringType(), True),
            StructField("changedBy", StringType(), True),
            StructField("changedById", StringType(), True),
        ]
    )

    _BULK_COMMON_FIELDS = [
        StructField("employeeId", StringType(), False),
        StructField("id", LongType(), False),
        StructField("effectiveDate", DateType(), True),
        StructField("activeEffectiveDate", DateType(), True),
        StructField("isCurrent", BooleanType(), True),
        StructField("canBeDeleted", BooleanType(), True),
        # Date-only ("YYYY-MM-DD") in production responses, not timestamps.
        StructField("creationDate", DateType(), True),
        StructField("modificationDate", DateType(), True),
        StructField("change", CHANGE_STRUCT, True),
        # Opaque object keyed by backend column IDs; stored as JSON string.
        StructField("customColumns", StringType(), True),
    ]

    # ---------------------------------------------------------------------------
    # Table schemas
    # ---------------------------------------------------------------------------

    EMPLOYEES_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("firstName", StringType(), True),
            StructField("surname", StringType(), True),
            StructField("email", StringType(), True),
            StructField("displayName", StringType(), True),
            StructField("fullName", StringType(), True),
            StructField("creationDateTime", TimestampType(), True),
            StructField(
                "work",
                StructType(
                    [
                        StructField("department", StringType(), True),
                        StructField("title", StringType(), True),
                        StructField("site", StringType(), True),
                        StructField("siteId", LongType(), True),
                        StructField("startDate", DateType(), True),
                        StructField("manager", StringType(), True),
                        StructField("reportsTo", EMPLOYEE_REF_STRUCT, True),
                    ]
                ),
                True,
            ),
            StructField(
                "internal",
                StructType(
                    [
                        StructField("status", StringType(), True),
                        StructField("lifecycleStatus", StringType(), True),
                        StructField("terminationDate", DateType(), True),
                    ]
                ),
                True,
            ),
            StructField(
                "personal",
                StructType([StructField("birthDate", DateType(), True)]),
                True,
            ),
            # Human-readable values (humanReadable=APPEND), as a JSON string.
            StructField("humanReadable", StringType(), True),
            # Full normalised employee record (incl. custom / extra fields), JSON.
            StructField("raw_json", StringType(), True),
        ]
    )

    EMPLOYEE_WORK_HISTORY_SCHEMA = StructType(
        _BULK_COMMON_FIELDS
        + [
            StructField("endEffectiveDate", DateType(), True),
            StructField("workChangeType", StringType(), True),
            StructField("department", StringType(), True),
            StructField("title", StringType(), True),
            StructField("site", StringType(), True),
            StructField("siteId", LongType(), True),
            StructField("reportsTo", EMPLOYEE_REF_STRUCT, True),
        ]
    )

    EMPLOYEE_EMPLOYMENT_HISTORY_SCHEMA = StructType(
        _BULK_COMMON_FIELDS
        + [
            StructField("endEffectiveDate", DateType(), True),
            StructField("contract", StringType(), True),
            StructField("type", StringType(), True),
            StructField("salaryPayType", StringType(), True),
            StructField("weeklyHours", DoubleType(), True),
            StructField("fte", DoubleType(), True),
            StructField("hoursInDayNotWorked", DoubleType(), True),
            StructField("calendarName", StringType(), True),
            StructField("calendarId", LongType(), True),
            StructField("flsaCode", StringType(), True),
            # Pattern shape varies by type (hourly / fortnightly / flexible).
            StructField("actualWorkingPattern", StringType(), True),
        ]
    )

    EMPLOYEE_LIFECYCLE_HISTORY_SCHEMA = StructType(
        _BULK_COMMON_FIELDS
        + [
            # Documented as a string for lifecycle entries.
            StructField("endEffectiveDate", StringType(), True),
            StructField("status", StringType(), True),
            StructField("employeeStatus", StringType(), True),
            StructField("reasonType", StringType(), True),
            StructField("leaveReason", StringType(), True),
        ]
    )

    TIME_OFF_REQUEST_CHANGES_SCHEMA = StructType(
        [
            StructField("changeType", StringType(), False),
            StructField("requestId", LongType(), False),
            StructField("originalRequestId", LongType(), True),
            StructField("previousRequestId", LongType(), True),
            StructField("employeeId", StringType(), True),
            StructField("employeeDisplayName", StringType(), True),
            StructField("employeeEmail", StringType(), True),
            StructField("policyTypeDisplayName", StringType(), True),
            StructField("type", StringType(), True),
            StructField("createdOn", TimestampType(), True),
            StructField("durationUnit", StringType(), True),
            StructField("totalDuration", DoubleType(), True),
            StructField("totalCost", DoubleType(), True),
            StructField("changeReason", StringType(), True),
            StructField("visibility", StringType(), True),
            StructField("startDate", DateType(), True),
            StructField("endDate", DateType(), True),
            StructField("timeZone", StringType(), True),
            # Type-specific fields (portions, start/end times, day durations...).
            StructField("additional_fields", StringType(), True),
        ]
    )

    NAMED_LISTS_SCHEMA = StructType(
        [
            StructField("list_name", StringType(), False),
            StructField("item_id", StringType(), False),
            StructField("value", StringType(), True),
            StructField("name", StringType(), True),
            StructField("archived", BooleanType(), True),
            StructField("parent_id", StringType(), True),
        ]
    )

    EMPLOYEE_FIELDS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("categoryId", StringType(), True),
            StructField("categoryDisplayName", StringType(), True),
            StructField("name", StringType(), True),
            StructField("description", StringType(), True),
            StructField("jsonPath", StringType(), True),
            StructField("type", StringType(), True),
            # Type-specific metadata (e.g. listId); stored as JSON string.
            StructField("typeData", StringType(), True),
            StructField("historical", BooleanType(), True),
        ]
    )

    CUSTOM_TABLE_COLUMN_STRUCT = StructType(
        [
            StructField("id", StringType(), True),
            StructField("name", StringType(), True),
            StructField("description", StringType(), True),
            StructField("mandatory", BooleanType(), True),
            StructField("type", StringType(), True),
            StructField("typeData", StringType(), True),
        ]
    )

    CUSTOM_TABLES_METADATA_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("category", StringType(), True),
            StructField("name", StringType(), True),
            StructField("description", StringType(), True),
            StructField("columns", ArrayType(CUSTOM_TABLE_COLUMN_STRUCT, True), True),
        ]
    )

    TABLE_SCHEMAS: dict[str, StructType] = {
        "employees": EMPLOYEES_SCHEMA,
        "employee_work_history": EMPLOYEE_WORK_HISTORY_SCHEMA,
        "employee_employment_history": EMPLOYEE_EMPLOYMENT_HISTORY_SCHEMA,
        "employee_lifecycle_history": EMPLOYEE_LIFECYCLE_HISTORY_SCHEMA,
        "time_off_request_changes": TIME_OFF_REQUEST_CHANGES_SCHEMA,
        "named_lists": NAMED_LISTS_SCHEMA,
        "employee_fields": EMPLOYEE_FIELDS_SCHEMA,
        "custom_tables_metadata": CUSTOM_TABLES_METADATA_SCHEMA,
    }

    _BULK_PK = ["employeeId", "id"]

    TABLE_METADATA: dict[str, dict] = {
        "employees": {"primary_keys": ["id"], "ingestion_type": "snapshot"},
        "employee_work_history": {"primary_keys": _BULK_PK, "ingestion_type": "snapshot"},
        "employee_employment_history": {"primary_keys": _BULK_PK, "ingestion_type": "snapshot"},
        "employee_lifecycle_history": {"primary_keys": _BULK_PK, "ingestion_type": "snapshot"},
        "time_off_request_changes": {
            "primary_keys": ["requestId", "changeType"],
            "cursor_field": "createdOn",
            "ingestion_type": "append",
        },
        "named_lists": {"primary_keys": ["list_name", "item_id"], "ingestion_type": "snapshot"},
        "employee_fields": {"primary_keys": ["id"], "ingestion_type": "snapshot"},
        "custom_tables_metadata": {"primary_keys": ["id"], "ingestion_type": "snapshot"},
    }

    # ---------------------------------------------------------------------------
    # company_report: dynamic schema (derived from the configured report's CSV
    # header at runtime), so it has no entry in TABLE_SCHEMAS / TABLE_METADATA.
    # ---------------------------------------------------------------------------

    COMPANY_REPORT_TABLE = "company_report"
    DYNAMIC_SCHEMA_TABLES = {COMPANY_REPORT_TABLE}
    # Report downloads can be several MB and are generated server-side on demand.
    REPORT_DOWNLOAD_TIMEOUT_SECONDS = 300

    SUPPORTED_TABLES = list(TABLE_SCHEMAS.keys()) + [COMPANY_REPORT_TABLE]

    # Tables read through the partitioned-stream path.
    PARTITIONED_TABLES = {"time_off_request_changes"}


    ########################################################
    # src/databricks/labs/community_connector/sources/hibob/hibob.py
    ########################################################

    logger = logging.getLogger(__name__)

    _TRUE_VALUES = {"true", "1", "yes", "y", "t"}
    _TIME_OFF_KNOWN_FIELDS = {f.name for f in TIME_OFF_REQUEST_CHANGES_SCHEMA.fields} - {
        "additional_fields"
    }


    class HibobLakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """LakeflowConnect implementation for HiBob.

        Connection options:
            service_user_id     Service User ID (Basic auth username). Required.
            service_user_token  Service User token (Basic auth password). Required.
            use_sandbox         "true" to target api.sandbox.hibob.com. Optional.
            base_url            Explicit API base URL override (incl. ``/v1``). Optional.

        Table options:
            employees:
                fields             Comma-separated extra field IDs to request
                                   (e.g. custom fields); appended to the defaults.
                show_inactive      Include non-employed people (default "true").
                human_readable     "", "APPEND" (default) or "REPLACE".
            employee_*_history:
                include_archived   Include archived entries (default "false").
                employee_ids       Comma-separated employee IDs to restrict to.
                page_size          Bulk page size, 1-200 (default 200).
            named_lists:
                include_archived   Include archived items (default "false").
            time_off_request_changes:
                start_date         ISO-8601 start for the initial load. Clamped to
                                   ``max_lookback_days`` (the API rejects older).
                window_days        Days per partition / window (default 7).
                max_lookback_days  Max history the API allows (default 180).
                include_pending    Include pending requests (default "false").
                max_records_per_batch
                                   Best-effort cap for the non-partitioned
                                   ``read_table`` path (default 1000). Windows are
                                   always fully drained (append-only table).
            company_report:
                report_id          ID of the saved HiBob report to download.
                                   Required.
                primary_keys       Comma-separated (or JSON list of) normalised
                                   column names to report as primary keys.
                                   Optional; when omitted no primary key is
                                   returned and the pipeline spec must supply one.
        """

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            self._user_id = options.get("service_user_id")
            self._token = options.get("service_user_token")
            if not self._user_id or not self._token:
                raise ValueError(
                    "HiBob connector requires 'service_user_id' and 'service_user_token'."
                )

            base_url = options.get("base_url")
            if not base_url:
                use_sandbox = _as_bool(options.get("use_sandbox"), default=False)
                base_url = SANDBOX_BASE_URL if use_sandbox else PRODUCTION_BASE_URL
            self._base_url = base_url.rstrip("/")

            # Offset cap: a trigger never chases data created after it started.
            self._init_time = _format_ts(datetime.now(timezone.utc))
            self._session_obj: requests.Session | None = None
            # report_id -> (header labels, data rows); avoids downloading the same
            # report twice for schema + metadata + read on one instance.
            self._report_cache: dict[str, tuple[list[str], list[list[str]]]] = {}

        # ------------------------------------------------------------------
        # Pickling: drop the live HTTP session (re-created lazily on executors).
        # ------------------------------------------------------------------

        def __getstate__(self) -> dict:
            state = self.__dict__.copy()
            state["_session_obj"] = None
            # Do not ship (potentially multi-MB) downloaded reports to executors.
            state["_report_cache"] = {}
            return state

        @property
        def _session(self) -> requests.Session:
            if self._session_obj is None:
                session = requests.Session()
                session.auth = (self._user_id, self._token)
                session.headers.update({"Accept": "application/json"})
                self._session_obj = session
            return self._session_obj

        # ------------------------------------------------------------------
        # LakeflowConnect: schema / metadata
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            self._validate_table(table_name)
            if table_name == COMPANY_REPORT_TABLE:
                columns = self._report_columns(table_options)
                return StructType([StructField(c, StringType(), True) for c in columns])
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            if table_name == COMPANY_REPORT_TABLE:
                return self._company_report_metadata(table_options)
            return dict(TABLE_METADATA[table_name])

        # ------------------------------------------------------------------
        # LakeflowConnect: read_table (single-driver path)
        # ------------------------------------------------------------------

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            if table_name == "time_off_request_changes":
                return self._read_time_off_incremental(start_offset, table_options)
            return iter(self._read_snapshot(table_name, table_options)), {}

        def _read_snapshot(self, table_name: str, table_options: dict[str, str]) -> list[dict]:
            if table_name == COMPANY_REPORT_TABLE:
                return self._read_company_report(table_options)
            if table_name == "employees":
                records = self._read_employees(table_options)
            elif table_name in BULK_TABLE_ENDPOINTS:
                records = self._read_bulk(table_name, table_options)
            elif table_name == "named_lists":
                records = self._read_named_lists(table_options)
            elif table_name == "employee_fields":
                records = self._read_employee_fields()
            elif table_name == "custom_tables_metadata":
                records = self._read_custom_tables_metadata()
            else:  # pragma: no cover - guarded by _validate_table
                raise ValueError(f"Unsupported table: {table_name}")
            schema = TABLE_SCHEMAS[table_name]
            return [_empty_structs_to_none(r, schema) for r in records]

        # ------------------------------------------------------------------
        # SupportsPartitionedStream
        # ------------------------------------------------------------------

        def is_partitioned(self, table_name: str) -> bool:
            return table_name in PARTITIONED_TABLES

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """No cheap high-water-mark endpoint exists; the init time is the cap.

            Returning the constant init time (or the committed offset if it is
            already past it) makes consecutive calls stable, which terminates
            ``Trigger.AvailableNow``.
            """
            self._validate_table(table_name)
            if table_name not in PARTITIONED_TABLES:
                # Snapshot tables are not read via the partitioned stream path.
                return {}
            current = (start_offset or {}).get("cursor")
            if current and _parse_ts(current) >= _parse_ts(self._init_time):
                return {"cursor": current}
            return {"cursor": self._init_time}

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            self._validate_table(table_name)

            if table_name not in PARTITIONED_TABLES:
                # Snapshot tables: one partition that performs the full read.
                if start_offset is None and end_offset is None:
                    return [{"snapshot": True}]
                if start_offset == end_offset:
                    return []
                return [{"snapshot": True}]

            if start_offset is not None and start_offset == end_offset:
                return []

            start_cursor = (start_offset or {}).get("cursor")
            end_cursor = (end_offset or {}).get("cursor") or self._init_time
            start_dt = self._resolve_time_off_start(start_cursor, table_options)
            end_dt = _parse_ts(end_cursor)
            if start_dt >= end_dt:
                return []

            window = timedelta(days=_as_int(table_options.get("window_days"),
                                            TIME_OFF_DEFAULT_WINDOW_DAYS, minimum=1))
            partitions: list[dict] = []
            cursor = start_dt
            while cursor < end_dt:
                nxt = min(cursor + window, end_dt)
                partitions.append({"since": _format_ts(cursor), "to": _format_ts(nxt)})
                cursor = nxt
            return partitions

        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            self._validate_table(table_name)
            if table_name not in PARTITIONED_TABLES:
                yield from self._read_snapshot(table_name, table_options)
                return
            yield from self._fetch_time_off_window(
                partition["since"], partition["to"], table_options
            )

        # ------------------------------------------------------------------
        # time_off_request_changes
        # ------------------------------------------------------------------

        def _resolve_time_off_start(
            self, cursor: str | None, table_options: dict[str, str]
        ) -> datetime:
            """Start of the (exclusive) range: offset > start_date > max lookback.

            Always clamped to ``init_time - max_lookback_days`` because the API
            errors when ``since`` is older than ~6 months.
            """
            max_lookback = _as_int(table_options.get("max_lookback_days"),
                                   TIME_OFF_DEFAULT_MAX_LOOKBACK_DAYS, minimum=1)
            floor = _parse_ts(self._init_time) - timedelta(days=max_lookback)
            raw = cursor or table_options.get("start_date")
            if not raw:
                return floor
            start = _parse_ts(raw)
            if start < floor:
                if cursor:
                    logger.warning(
                        "HiBob time_off_request_changes: checkpoint %s is older than the "
                        "API's %d-day lookback limit; changes between %s and %s cannot be "
                        "fetched.", cursor, max_lookback, cursor, _format_ts(floor),
                    )
                return floor
            return start

        def _read_time_off_incremental(
            self, start_offset: dict | None, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Sliding-window read for the single-driver path.

            Consecutive windows are drained until ``max_records_per_batch`` is
            reached (best-effort: windows are never truncated since the table is
            append-only) or the init-time cap is hit.
            """
            cursor = (start_offset or {}).get("cursor")
            if cursor and _parse_ts(cursor) >= _parse_ts(self._init_time):
                return iter([]), start_offset

            since_dt = self._resolve_time_off_start(cursor, table_options)
            init_dt = _parse_ts(self._init_time)
            if since_dt >= init_dt:
                end_offset = {"cursor": self._init_time}
                return iter([]), start_offset if start_offset else end_offset

            window = timedelta(days=_as_int(table_options.get("window_days"),
                                            TIME_OFF_DEFAULT_WINDOW_DAYS, minimum=1))
            max_records = _as_int(table_options.get("max_records_per_batch"),
                                  TIME_OFF_DEFAULT_MAX_RECORDS_PER_BATCH, minimum=1)

            records: list[dict] = []
            window_start = since_dt
            while window_start < init_dt and len(records) < max_records:
                window_end = min(window_start + window, init_dt)
                records.extend(self._fetch_time_off_window(
                    _format_ts(window_start), _format_ts(window_end), table_options
                ))
                window_start = window_end

            end_offset = {"cursor": _format_ts(window_start)}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset
            return iter(records), end_offset

        def _fetch_time_off_window(
            self, since: str, to: str, table_options: dict[str, str]
        ) -> list[dict]:
            """Fetch changes with ``since < createdOn <= to``.

            The server-side filter bounds the scan; the client-side check makes
            adjacent windows disjoint regardless of the API's boundary semantics.
            """
            params = {
                "since": since,
                "to": to,
                "includePending": "true" if _as_bool(
                    table_options.get("include_pending"), default=False) else "false",
            }
            body = self._get_json("/timeoff/requests/changes", params=params)
            since_dt, to_dt = _parse_ts(since), _parse_ts(to)
            out: list[dict] = []
            for change in body.get("changes") or []:
                created = change.get("createdOn")
                if created:
                    try:
                        created_dt = _parse_ts(created)
                    except ValueError:
                        created_dt = None
                    if created_dt is not None and not since_dt < created_dt <= to_dt:
                        continue
                out.append(_normalize_time_off_change(change))
            return out

        # ------------------------------------------------------------------
        # employees
        # ------------------------------------------------------------------

        def _read_employees(self, table_options: dict[str, str]) -> list[dict]:
            fields = list(DEFAULT_EMPLOYEE_FIELDS)
            for extra in (table_options.get("fields") or "").split(","):
                extra = extra.strip()
                if extra and extra not in fields:
                    fields.append(extra)
            if len(fields) > MAX_EMPLOYEE_FIELDS:
                raise ValueError(
                    f"HiBob people search accepts at most {MAX_EMPLOYEE_FIELDS} fields; "
                    f"got {len(fields)}."
                )
            human_readable = table_options.get("human_readable", "APPEND")
            human_readable = (human_readable or "").upper()
            if human_readable not in HUMAN_READABLE_MODES:
                raise ValueError(
                    f"human_readable must be one of {sorted(HUMAN_READABLE_MODES)}; "
                    f"got {human_readable!r}"
                )
            # Never send ``filters`` (an empty list is rejected with 400).
            payload = {
                "fields": fields,
                "showInactive": _as_bool(table_options.get("show_inactive"), default=True),
                "humanReadable": human_readable,
            }
            body = self._request_json("POST", "/people/search", json_body=payload)
            return [_normalize_employee(e) for e in body.get("employees") or []]

        # ------------------------------------------------------------------
        # Bulk history tables
        # ------------------------------------------------------------------

        def _read_bulk(self, table_name: str, table_options: dict[str, str]) -> list[dict]:
            path = f"/bulk/people/{BULK_TABLE_ENDPOINTS[table_name]}"
            page_size = _as_int(table_options.get("page_size"), BULK_DEFAULT_PAGE_SIZE,
                                minimum=1, maximum=BULK_MAX_PAGE_SIZE)
            base_params: dict[str, str] = {
                "limit": str(page_size),
                "includeArchived": "true" if _as_bool(
                    table_options.get("include_archived"), default=False) else "false",
            }
            employee_ids = [
                e.strip() for e in (table_options.get("employee_ids") or "").split(",") if e.strip()
            ]
            id_chunks: list[list[str] | None] = (
                [employee_ids[i:i + BULK_MAX_EMPLOYEE_IDS]
                 for i in range(0, len(employee_ids), BULK_MAX_EMPLOYEE_IDS)]
                if employee_ids else [None]
            )

            rows: list[dict] = []
            for chunk in id_chunks:
                params = dict(base_params)
                if chunk:
                    params["employeeIds"] = ",".join(chunk)
                seen_cursors: set[str] = set()
                while True:
                    body = self._get_json(path, params=params)
                    for result in body.get("results") or []:
                        emp_id = result.get("employeeId")
                        for entry in result.get("values") or []:
                            rows.append(_normalize_bulk_entry(entry, emp_id))
                    _log_bulk_errors(table_name, body.get("errors"))
                    next_cursor = (body.get("response_metadata") or {}).get("next_cursor")
                    if not next_cursor or next_cursor in seen_cursors:
                        break
                    seen_cursors.add(next_cursor)
                    # requests URL-encodes query params.
                    params["cursor"] = next_cursor
            return rows

        # ------------------------------------------------------------------
        # Reference tables
        # ------------------------------------------------------------------

        def _read_named_lists(self, table_options: dict[str, str]) -> list[dict]:
            params = {
                "includeArchived": "true" if _as_bool(
                    table_options.get("include_archived"), default=False) else "false",
            }
            body = self._get_json("/company/named-lists", params=params)
            rows: list[dict] = []
            for named_list in _iter_named_lists(body):
                list_name = named_list.get("name")
                _flatten_list_items(list_name, named_list.get("items") or [], None, rows, 0)
            return rows

        def _read_employee_fields(self) -> list[dict]:
            body = self._get_json("/company/people/fields")
            fields = body.get("fields") if isinstance(body, dict) else body
            out = []
            for field in fields or []:
                rec = dict(field)
                rec["typeData"] = _to_json(rec.get("typeData"))
                out.append(rec)
            return out

        def _read_custom_tables_metadata(self) -> list[dict]:
            body = self._get_json("/people/custom-tables/metadata")
            out = []
            for table in body.get("tables") or []:
                rec = dict(table)
                columns = []
                for col in rec.get("columns") or []:
                    col = dict(col)
                    col["typeData"] = _to_json(col.get("typeData"))
                    columns.append(col)
                rec["columns"] = columns
                out.append(rec)
            return out

        # ------------------------------------------------------------------
        # company_report
        # ------------------------------------------------------------------

        def _company_report_metadata(self, table_options: dict[str, str]) -> dict:
            report_id = _require_report_id(table_options)
            metadata: dict[str, Any] = {"ingestion_type": "snapshot"}
            raw_pks = table_options.get("primary_keys")
            pks = _parse_name_list(raw_pks)
            if raw_pks not in (None, "") and not pks:
                raise ValueError(
                    f"company_report: 'primary_keys' option {raw_pks!r} contains no column names."
                )
            if pks:
                columns = self._report_columns(table_options)
                missing = [pk for pk in pks if pk not in columns]
                if missing:
                    raise ValueError(
                        f"company_report: primary_keys {missing} are not columns of report "
                        f"{report_id}. Use normalised column names; available columns: {columns}"
                    )
                metadata["primary_keys"] = pks
            return metadata

        def _report_columns(self, table_options: dict[str, str]) -> list[str]:
            header, _ = self._download_report(_require_report_id(table_options))
            return normalize_report_columns(header)

        def _read_company_report(self, table_options: dict[str, str]) -> list[dict]:
            report_id = _require_report_id(table_options)
            header, rows = self._download_report(report_id)
            columns = normalize_report_columns(header)
            width = len(columns)
            out: list[dict] = []
            overflow = 0
            for row in rows:
                if len(row) > width:
                    overflow += 1
                values = list(row[:width]) + [""] * (width - len(row))
                out.append({c: (v if v != "" else None) for c, v in zip(columns, values)})
            if overflow:
                logger.warning(
                    "HiBob company_report %s: %d row(s) had more cells than the header; "
                    "extra cells were dropped.", report_id, overflow,
                )
            return out

        def _download_report(self, report_id: str) -> tuple[list[str], list[list[str]]]:
            """Download a saved report as CSV; returns ``(header, data_rows)``.

            Cached per ``report_id`` on this instance. The body is UTF-8 with an
            optional BOM; fully blank lines are skipped.
            """
            cached = self._report_cache.get(report_id)
            if cached is not None:
                return cached
            path = f"/company/reports/{quote(report_id, safe='')}/download"
            resp = self._request_with_retry(
                "GET",
                path,
                params={"format": "csv"},
                headers={"Accept": "text/csv, */*"},
                timeout=REPORT_DOWNLOAD_TIMEOUT_SECONDS,
            )
            if resp.status_code >= 400:
                hint = {
                    401: "invalid service user credentials",
                    403: "the service user lacks permission to this report or its fields",
                    404: ("report not found, or not shared with the service user; it must "
                          "be visible in GET /company/reports"),
                    429: "rate limit exceeded after retries",
                }.get(resp.status_code, "request failed")
                raise RuntimeError(
                    f"HiBob API GET {path} returned {resp.status_code} ({hint}): "
                    f"{resp.text[:500]}"
                )
            text = resp.content.decode("utf-8-sig")
            reader = csv.reader(io.StringIO(text, newline=""))
            rows = [r for r in reader if r and any(cell != "" for cell in r)]
            if not rows:
                raise RuntimeError(
                    f"HiBob report {report_id} download returned no CSV header row."
                )
            result = (rows[0], rows[1:])
            self._report_cache[report_id] = result
            return result

        # ------------------------------------------------------------------
        # HTTP helpers
        # ------------------------------------------------------------------

        def _get_json(self, path: str, params: dict | None = None) -> dict:
            return self._request_json("GET", path, params=params)

        def _request_json(
            self,
            method: str,
            path: str,
            params: dict | None = None,
            json_body: dict | None = None,
        ) -> dict:
            resp = self._request_with_retry(method, path, params=params, json_body=json_body)
            if resp.status_code >= 400:
                hint = {
                    400: "bad request (invalid field, filter or parameter)",
                    401: "invalid service user credentials",
                    403: "service user lacks the required category permission or audience",
                    404: "endpoint not found",
                    429: "rate limit exceeded after retries",
                }.get(resp.status_code, "request failed")
                raise RuntimeError(
                    f"HiBob API {method} {path} returned {resp.status_code} ({hint}): "
                    f"{resp.text[:500]}"
                )
            if not resp.content:
                return {}
            return resp.json()

        def _request_with_retry(
            self,
            method: str,
            path: str,
            params: dict | None = None,
            json_body: dict | None = None,
            headers: dict | None = None,
            timeout: float = REQUEST_TIMEOUT_SECONDS,
        ) -> requests.Response:
            url = f"{self._base_url}{path}"
            backoff = INITIAL_BACKOFF_SECONDS
            resp: requests.Response | None = None
            for attempt in range(MAX_RETRIES):
                try:
                    resp = self._session.request(
                        method,
                        url,
                        params=params,
                        json=json_body,
                        headers=headers,
                        timeout=timeout,
                    )
                except (requests.ConnectionError, requests.Timeout):
                    if attempt == MAX_RETRIES - 1:
                        raise
                    time.sleep(backoff)
                    backoff = min(backoff * 2, MAX_BACKOFF_SECONDS)
                    continue

                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    return resp
                if attempt < MAX_RETRIES - 1:
                    time.sleep(_retry_wait_seconds(resp, backoff))
                    backoff = min(backoff * 2, MAX_BACKOFF_SECONDS)
            return resp  # type: ignore[return-value]

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLE_SCHEMAS and table_name not in DYNAMIC_SCHEMA_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported tables: {SUPPORTED_TABLES}"
                )


    # ---------------------------------------------------------------------------
    # Module-level helpers
    # ---------------------------------------------------------------------------


    _NON_ALNUM_RE = re.compile(r"[^a-z0-9]+")


    def normalize_report_column(label: str) -> str:
        """Normalise one report header label to a snake_case, Spark-safe name.

        Accents are stripped (NFKD → ASCII), the text is lower-cased, every run
        of characters outside ``[a-z0-9]`` becomes a single ``_`` and leading /
        trailing underscores are removed. E.g. ``"Employee ID (bob)"`` →
        ``"employee_id_bob"``, ``"Manager's ID"`` → ``"manager_s_id"``. Returns
        ``""`` when nothing alphanumeric remains.
        """
        ascii_label = (
            unicodedata.normalize("NFKD", label or "").encode("ascii", "ignore").decode("ascii")
        )
        return _NON_ALNUM_RE.sub("_", ascii_label.lower()).strip("_")


    def normalize_report_columns(labels: Sequence[str]) -> list[str]:
        """Normalise header labels and make them unique.

        Labels that normalise to an empty string become ``column_<n>`` (1-based
        position). Collisions get a numeric suffix in header order: the first
        occurrence keeps the bare name, later ones become ``<name>_2``,
        ``<name>_3``, ... (skipping any suffix that is already taken).
        """
        names: list[str] = []
        used: set[str] = set()
        for position, label in enumerate(labels, start=1):
            base = normalize_report_column(label) or f"column_{position}"
            name = base
            suffix = 2
            while name in used:
                name = f"{base}_{suffix}"
                suffix += 1
            used.add(name)
            names.append(name)
        return names


    def _require_report_id(table_options: dict[str, str]) -> str:
        report_id = str(table_options.get("report_id") or "").strip()
        if not report_id:
            raise ValueError(
                "Table 'company_report' requires the 'report_id' table option (the ID of a "
                "saved HiBob report shared with the service user; list them with "
                "GET /company/reports)."
            )
        return report_id


    def _parse_name_list(raw: Any) -> list[str]:
        """Parse ``"a,b"`` / ``'["a","b"]'`` / a list into stripped, non-empty names."""
        if raw is None:
            return []
        if isinstance(raw, (list, tuple)):
            items = list(raw)
        else:
            text = str(raw).strip()
            if text.startswith("["):
                try:
                    parsed = json.loads(text)
                except ValueError as exc:
                    raise ValueError(f"Invalid JSON list for primary_keys: {text!r}") from exc
                items = parsed if isinstance(parsed, list) else [parsed]
            else:
                items = text.split(",")
        out: list[str] = []
        for item in items:
            name = str(item).strip()
            if name and name not in out:
                out.append(name)
        return out


    def _retry_wait_seconds(resp: requests.Response, backoff: float) -> float:
        """Honour ``X-RateLimit-Reset`` (Unix ts) then ``Retry-After``, else backoff."""
        reset = resp.headers.get("X-RateLimit-Reset")
        if reset:
            try:
                wait = float(reset) - time.time()
                if wait > 0:
                    return min(wait + 0.5, MAX_BACKOFF_SECONDS)
            except (TypeError, ValueError):
                pass
        retry_after = resp.headers.get("Retry-After")
        if retry_after:
            try:
                return min(max(float(retry_after), 0.0), MAX_BACKOFF_SECONDS)
            except (TypeError, ValueError):
                pass
        return backoff


    def _as_bool(value: Any, default: bool) -> bool:
        if value is None or value == "":
            return default
        if isinstance(value, bool):
            return value
        return str(value).strip().lower() in _TRUE_VALUES


    def _as_int(value: Any, default: int, minimum: int | None = None,
                maximum: int | None = None) -> int:
        try:
            result = int(value) if value not in (None, "") else default
        except (TypeError, ValueError):
            result = default
        if minimum is not None:
            result = max(minimum, result)
        if maximum is not None:
            result = min(maximum, result)
        return result


    def _parse_ts(value: str) -> datetime:
        """Parse an ISO-8601 date / datetime; naive values are treated as UTC."""
        text = value.strip()
        if text.endswith("Z"):
            text = text[:-1] + "+00:00"
        dt = datetime.fromisoformat(text)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc)


    def _format_ts(dt: datetime) -> str:
        return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


    def _to_json(value: Any) -> str | None:
        if value is None:
            return None
        if isinstance(value, str):
            return value
        if isinstance(value, (dict, list)) and not value:
            return None
        return json.dumps(value, sort_keys=True, default=str)


    def _as_employee_ref(value: Any) -> dict | None:
        if value is None or value == "" or value == {}:
            return None
        if isinstance(value, dict):
            return value
        return {"id": str(value)}


    def _empty_structs_to_none(value: Any, data_type: Any) -> Any:
        """Recursively replace ``{}`` with ``None`` for StructType-typed fields."""
        if isinstance(data_type, StructType):
            if not isinstance(value, dict):
                return value
            if not value:
                return None
            out = dict(value)
            for field in data_type.fields:
                if field.name in out:
                    out[field.name] = _empty_structs_to_none(out[field.name], field.dataType)
            return out
        if isinstance(data_type, ArrayType) and isinstance(value, list):
            return [_empty_structs_to_none(v, data_type.elementType) for v in value]
        return value


    def _normalize_employee(raw: dict) -> dict:
        """Merge flat slash keys (``"/work/title": {"value": ...}``) into nested form.

        ``/root/<x>`` maps to the top level; ``/<category>/<x>`` to
        ``record[category][x]``. Existing nested values take precedence.
        """
        record: dict = copy.deepcopy({k: v for k, v in raw.items() if not k.startswith("/")})
        for key, val in raw.items():
            if not key.startswith("/"):
                continue
            parts = [p for p in key.strip("/").split("/") if p]
            if not parts:
                continue
            if isinstance(val, dict) and "value" in val:
                val = val["value"]
            if parts[0] == "root":
                parts = parts[1:]
                if not parts:
                    continue
            cur = record
            for part in parts[:-1]:
                nxt = cur.get(part)
                if not isinstance(nxt, dict):
                    nxt = {}
                    cur[part] = nxt
                cur = nxt
            cur.setdefault(parts[-1], val)

        work = record.get("work")
        if isinstance(work, dict) and "reportsTo" in work:
            work = dict(work)
            work["reportsTo"] = _as_employee_ref(work.get("reportsTo"))
            record["work"] = work
        if record.get("id") is not None:
            record["id"] = str(record["id"])
        record["raw_json"] = json.dumps(raw, sort_keys=True, default=str)
        record["humanReadable"] = _to_json(record.get("humanReadable"))
        return record


    def _normalize_bulk_entry(entry: dict, employee_id: Any) -> dict:
        row = dict(entry)
        if employee_id is not None:
            row["employeeId"] = str(employee_id)
        for key in BULK_JSON_FIELDS:
            if key in row:
                row[key] = _to_json(row[key])
        if "reportsTo" in row:
            row["reportsTo"] = _as_employee_ref(row.get("reportsTo"))
        if row.get("change") == {}:
            row["change"] = None
        return row


    def _normalize_time_off_change(change: dict) -> dict:
        row = {k: v for k, v in change.items() if k in _TIME_OFF_KNOWN_FIELDS}
        extras = {k: v for k, v in change.items() if k not in _TIME_OFF_KNOWN_FIELDS}
        if "additional_fields" in extras and len(extras) == 1:
            # Already-normalised record (e.g. corpus replay) — keep as-is.
            row["additional_fields"] = _to_json(extras["additional_fields"])
        else:
            row["additional_fields"] = _to_json(extras) if extras else None
        return row


    def _iter_named_lists(body: Any) -> Iterator[dict]:
        """Yield list dicts from either ``{"lists": [...]}`` or a name-keyed map."""
        if not isinstance(body, dict):
            return
        lists = body.get("lists", body)
        if isinstance(lists, list):
            for item in lists:
                if isinstance(item, dict):
                    yield item
        elif isinstance(lists, dict):
            for name, item in lists.items():
                if isinstance(item, dict):
                    if not item.get("name"):
                        item = {**item, "name": name}
                    yield item


    def _flatten_list_items(
        list_name: Any, items: list, parent_id: str | None, out: list[dict], depth: int
    ) -> None:
        if depth > NAMED_LIST_MAX_DEPTH:
            return
        for item in items:
            if not isinstance(item, dict):
                continue
            item_id = item.get("id")
            item_id = str(item_id) if item_id is not None else None
            out.append({
                "list_name": list_name,
                "item_id": item_id,
                "value": item.get("value"),
                "name": item.get("name"),
                "archived": item.get("archived"),
                "parent_id": parent_id,
            })
            children = item.get("children") or []
            if children:
                _flatten_list_items(list_name, children, item_id, out, depth + 1)


    def _log_bulk_errors(table_name: str, errors: Any) -> None:
        if not errors:
            return
        count = len(errors) if isinstance(errors, list) else 1
        sample = errors[:3] if isinstance(errors, list) else errors
        logger.warning(
            "HiBob %s: %d employee(s) skipped due to per-employee errors "
            "(e.g. MISSING_PERMISSION). Sample: %s", table_name, count, sample,
        )


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = HibobLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
